# Generated by Django 5.2.5 on 2025-09-04 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Berita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('isi', models.TextField()),
                ('kategori', models.CharField(max_length=100)),
                ('penulis', models.CharField(max_length=100)),
                ('tanggal_publikasi', models.DateTimeField(auto_now_add=True)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='gambar_berita/')),
            ],
        ),
    ]
